services:
  backend:
    container-name: tpi-scraper-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${URL_POSTGRES}
      SPRING_DATASOURCE_USERNAME: ${USER_ERP_FREELANCE}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD_POSTGRESQL}
    networks:
      - tpi-scraping-network

networks:
  erp-freelance-network:
    name: tpi-scraping-network
    driver: bridge

    